### ISSUE TITLE
python version 2 or 3?

### ISSUE THREAD

**Issue by mfs370** [bwiley1/pandleau#1]
Hi Benjamin,

I am kind of new to python and eager to use your library to make it easy to switch between python and tableau. I have the following question: one of the libraries that is used by your module is  'tableausdk'. it seems that this is a python 2 version only, or am i wrong? 

I am trying to pip install your module but it keeps giving me version mismatch errors ( i run on py 3.6).
Thanks in advance!

Melvin

![image](https://user-images.githubusercontent.com/19540650/38839484-24aace1a-41db-11e8-998d-0f8c337ecef4.png)

**Comment by bwiley1** [comment]
Hi Melvin,

Thanks for the question. The tableausdk module is supported in Python 2, but I am running Python 3.6.1 and am still able to use it. That said, I did not download tableausdk using pip - instead, I downloaded the module directly from Tableau's site: 

- [https://onlinehelp.tableau.com/current/api/sdk/en-us/SDK/tableau_sdk_installing.htm](url)

Let me know if that helps!

**Comment by bwiley1** [comment]
Hi Melvin,

I just wanted to follow up on this issue with you. I have updated the package to run in Python 2, which I think makes more sense given that tableausdk was designed in this version. Let me know if you run into any additional problems, thanks!
