### ISSUE TITLE
unicode column types in pandas 0.23.0

### ISSUE THREAD

**Issue by ZamoraAndres** [bwiley1/pandleau#14]
pandleau.py
In the mapper dictionary (line 37), could you add the following data type:
'unicode':Type.UNICODE_STRING
Thank you!

**Comment by bwiley1** [comment]
Hi! Sure, I think that right now the `UNICODE_STRING` is currently indexed under `string` in the mapper dictionary, while `CHAR_STRING` is under `categorical`. Hopefully this helps!
