### ISSUE TITLE
Publish to pypi without tableausdk dependency?

### ISSUE THREAD

**Issue by gitmstoute** [bwiley1/pandleau#23]
In recent commits of setup.py the requirement for tableausdk was dropped. Is it possible publish a version with this change to pypi? 
I'm including pandleau in some docker containers, and because I can't pip/pipenv install pandleau, it makes the docker build more complex. 

Thanks in advance!

**Comment by bwiley1** [comment]
Sure, I'll add the updated version to pypi tonight. Thanks!

**Comment by gitmstoute** [comment]
Thanks @bwiley1 - however I just found the workaround was dead simple, so feel free to just proceed and release at your own pace.

**Comment by bwiley1** [comment]
Updated :)

**Comment by gitmstoute** [comment]
Amazing, thanks!
