### ISSUE TITLE
__init__.py

### ISSUE THREAD

**Issue by RPerk22** [bwiley1/pandleau#5]
----
from pandleau import pandleau
You are using the Tableau SDK, please save the output as .tde format

ImportErrorTraceback (most recent call last)
<ipython-input-1-5b7bc769724d> in <module>()
----> 1 from pandleau import pandleau

C:\Users\perkir1\AppData\Local\Continuum\anaconda2\lib\site-packages\pandleau\__init__.py in <module>()
----> 1 from pandleau.pandleau import *

ImportError: No module named pandleau
----

package having issues w/ __init__.py file.  Returns no module named pandleau import error.

**Comment by RPerk22** [comment]
changing to 'from pandleau import *' seems to fix issue.

**Comment by bwiley1** [comment]
Awesome, I'll update the example on the README file. Thanks for point this out!
